- name: Update ubuntu & debian linux
  ansible.builtin.command: apt update
  changed_when:
    - ansible_distribution == 'Debian'
    - ansible_distribution == 'Ubuntu'

- name: Install system updates for centos systems
  ansible.builtin.yum:
    name: '*'
    state: present
    update_cache: true
    # cache_valid_time: 3600
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "CentOS"

- name: Install system updates for ubuntu systems
  apt:
    name: '*'
    state: present
    update_cache: true
    # cache_valid_time: 3600
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution == "Ubuntu"
